apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sy09lsf4e-python
  janus-idp.io/tekton: sy09lsf4e-python
  backstage.io/kubernetes-id: sy09lsf4e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sy09lsf4e-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
